# Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [1]:
# importing the NumPy library

import numpy as np

In [5]:
# creating an array with 4 elements and increments of a fixed step size
# default step size is one
np_1 = np.arange(1,5)


# creating an array of zeroes with 5 elements
np_2 = np.zeros(5)

In [6]:
# checking the created array: np_1
print(np_1)

[1 2 3 4]


In [7]:
# checking the created array:np_2
print(np_2)

[0. 0. 0. 0. 0.]


In [9]:
# data type of np_2
np_2.dtype

dtype('float64')

In [20]:
# specifying the data type of the array in the provided attribute

np_3=np.arange(1,5,dtype='int')
print(np_3)
np_3.dtype

[1 2 3 4]


dtype('int64')

In [18]:
# adding the two arrays: np_1 and np_2
print(np_1 + np_2)
#We get an error bcs the sizes are different

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [21]:
# check the dimension of the arrays
# array np_1
np_1.size

4

In [25]:
# check the dimension of the arrays
# array np_2
np_2.size

5

In [26]:
# creating a third array with all the 5 elements as ones

np_3 = np.ones(5)

# checking the created array:np_3
print(np_3)

[1. 1. 1. 1. 1.]


In [27]:
# check the dimension of the arrays
# array np_2
np_2.size

5

In [28]:
# subtracting the array np_3 from array np_2

print(np_2 - np_3)

[-1. -1. -1. -1. -1.]


In [30]:
# creating an array of fixed length
np_4 = np.zeros(4)

# checking the created array:np_4
print(np_4)

[0. 0. 0. 0.]


In [31]:
# checking the created array:np_1
np_1

array([1, 2, 3, 4])

In [33]:
# squaring the terms of np_1
np_1**2

array([ 1,  4,  9, 16])

In [39]:
# getting the absolute value of the elements
np.abs(np_1)

array([1, 2, 3, 4])

In [37]:
# np.sin()
np.sin(np_1)
# np.cos()
np.cos(np_1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [38]:
# np.log()
np.log(np_1)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

### Empty arrays

In [43]:
# Creating empty arrays

x = np.arange(1, 6)
y = np.zeros(shape=(1,6))

# filling the empty array
y=x

In [44]:
# printing the output obtained above
y

array([1, 2, 3, 4, 5])

### Aggregation of array elements

In [57]:
# Reducing the elements to a single value based on addition
np.add.reduce(np_1)

10

In [60]:
# Cummulative addition of elements at each element
np.add.accumulate(np_1)

array([ 1,  3,  6, 10])

In [47]:
np.linalg

<module 'numpy.linalg' from '/Users/apple/opt/anaconda3/lib/python3.9/site-packages/numpy/linalg/__init__.py'>

In [13]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

## Additional functions to initialize arrays in NumPy

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
* ```np.random.random()```: Create array of random numbers between 0 and 1
-  `np.random.randint()`: Create a random array of integers within a particular range

In [48]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [49]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [50]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [51]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [52]:
# Create a 3 x 3 array of random numbers between 0 and 1
np.random.random([3, 4])

array([[0.64065721, 0.16030261, 0.65891055, 0.24545805],
       [0.43745903, 0.27602382, 0.44042842, 0.2031052 ],
       [0.70029864, 0.32730486, 0.31811126, 0.95106089]])

In [53]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))

array([[7, 9, 1, 0],
       [3, 3, 4, 0],
       [5, 9, 8, 7],
       [3, 7, 6, 5]])